package com.amazonaws.lambda.isnewcourse;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.*;

@XmlRootElement
@DynamoDBTable(tableName ="course")
public class Course {

    private String Id;
    private String courseId;
    private String professorId;
    private String TAId;
    private String department;
    private String boardId;
    private List<String> enrolledStudent;
    private String notificationTopic;
    private String status;

    public Course(){
        this.Id = null;
        this.courseId = null;
        this.professorId = null;
        this.TAId = null;
        this.department = null;

    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "courseId-index")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName = "professorId")
    public String getProfessorId() {
        return professorId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    @DynamoDBAttribute(attributeName = "TAId")
    public String getTAId() {
        return TAId;
    }

    public void setTAId(String TAId) {
        this.TAId = TAId;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "boardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "enrolledStudent")
    public List<String> getEnrolledStudent() {
        return enrolledStudent;
    }

    public void setEnrolledStudent(List<String> enrolledStudent) {
        this.enrolledStudent = enrolledStudent;
    }

    @DynamoDBAttribute(attributeName = "notificationTopic")
    public String getNotificationTopic() {
        return notificationTopic;
    }

    public void setNotificationTopic(String notificationTopic) {
        this.notificationTopic = notificationTopic;
    }
    
    @DynamoDBIgnore
    public String getStatus() {
    	return status;
    }

    public void setStatus(String status) {
    	this.status = status;
    }
    @Override
    public String toString() {
        return "Course{" +
                "Id='" + Id + '\'' +
                ", courseId='" + courseId + '\'' +
                ", professorId='" + professorId + '\'' +
                ", TAId='" + TAId + '\'' +
                ", department='" + department + '\'' +
                ", boardId='" + boardId + '\'' +
                ", enrolledStudent=" + enrolledStudent +
                ", notificationTopic='" + notificationTopic + '\'' +
                ", status='" + status + '\'' +
                '}';
    }
}
