package com.amazonaws.lambda.register;
import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@XmlRootElement
@DynamoDBTable(tableName ="registrar")
public class Registrar {
    private String Id;
    private String registrationId;
    private String offeringId;//courseId
    private String offeringType;
    private String department;
    private String perUnitPrice;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "registrarId", globalSecondaryIndexName = "registrarId-index")
    public String getRegistrationId() {
        return registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    @DynamoDBAttribute(attributeName = "offeringId")
    public String getOfferingId() {
        return offeringId;
    }

    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId;
    }

    @DynamoDBAttribute(attributeName = "offeringType")
    public String getOfferingType() {
        return offeringType;
    }

    public void setOfferingType(String offeringType) {
        this.offeringType = offeringType;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "perUnitPrice")
    public String getPerUnitPrice() {
        return perUnitPrice;
    }

    public void setPerUnitPrice(String perUnitPrice) {
        this.perUnitPrice = perUnitPrice;
    }

    @Override
    public String toString() {
        return "Registrar{" +
                "Id='" + Id + '\'' +
                ", offeringId='" + offeringId + '\'' +
                ", offeringType='" + offeringType + '\'' +
                ", department='" + department + '\'' +
                ", perUnitPrice='" + perUnitPrice + '\'' +
                '}';
    }
}

